services:
    _defaults:
        autowire: true
        autoconfigure: true

    Adeliom\EasyFieldsBundle\Form\Extension\:
        resource: '../../Form/Extension/'

    Adeliom\EasyFieldsBundle\Controller\OembedController:
        public: true

    Adeliom\EasyFieldsBundle\Form\SortableCollectionType:
        public: true

    Adeliom\EasyFieldsBundle\Admin\Field\Configurator\SortableCollectionConfigurator:
        public: true

    Adeliom\EasyFieldsBundle\Admin\Field\Configurator\AssociationConfigurator:
        public: true

    Adeliom\EasyFieldsBundle\Form\ChoiceMaskType:
        public: true

    Adeliom\EasyFieldsBundle\Admin\Field\Configurator\ChoiceMaskConfigurator:
        public: true

    Adeliom\EasyFieldsBundle\Admin\Field\Configurator\EnumConfigurator:
        public: true

    Adeliom\EasyFieldsBundle\Admin\Field\Configurator\PositionSortableConfigurator:
        public: true

    Adeliom\EasyFieldsBundle\Twig\OembedExtension:
        public: true
        tags: [twig.extension]


    Adeliom\EasyFieldsBundle\EventListener\AdminListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }
